### ISSUE TITLE
[Helm Chart] Ingress template is not working

### ISSUE THREAD

**Issue by elwood218** [tribe29/checkmk_kube_agent#3]
Hello,

the ingress template was not working for me. It got a little mistake:

https://github.com/tribe29/checkmk_kube_agent/blob/main/deploy/charts/checkmk/templates/cluster-collector-ingress.yaml (Master is only an example - I was using the 1.0.0 - but both got the problem)

```
rules:
    {{- range .Values.clusterCollector.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "checkmk.fullname" . }}-cluster-collector
                port:
                  number: {{ .Values.clusterCollector.service.port }}
          {{- end }}
    {{- end }}
```

In a range the `.` is the value of the hosts list you put there. So you have to put a `$` to access other values. This concludes to adjust those lines:

```
                name: {{ include "checkmk.fullname" $ }}-cluster-collector
                port:
                  number: {{ $.Values.clusterCollector.service.port }}
```
