### ISSUE TITLE
Unknown capability to add: "CAP_CAP_SYS_PTRACE" Error in node collector metrics container (OTC CCE with EulerOS)

### ISSUE THREAD

**Issue by arkadiusjonczek** [tribe29/checkmk_kube_agent#7]
Hello folks,

we are using Cluster Container Engine (Managed Kubernetes with EulerOS Nodes) in Open Telekom Cloud.

While installing the helm chart (latest version) we get the following error in node collector metrics container:

```
Error: failed to start container "cadvisor": Error response from daemon: linux spec capabilities: Unknown capability to add: "CAP_CAP_SYS_PTRACE"
```

Can you help us with this problem?

Best regards,
Arkadius

**Comment by lisa-pi** [comment]
Hi @arkadiusjonczek , 

Please be aware we're currently only supporting vanilla Kubernetes v1.21-1.23 and the container runtimes Docker and containerd, as explained in our [README](https://github.com/tribe29/checkmk_kube_agent#readme).

Having said that, I think I know what the problem is. Have a look at your values.yaml, specifically the securityContext section of the cAdvisor container: 

```
...
  cadvisor:
      ...

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add: ["CAP_SYS_PTRACE"]
      privileged: false
      readOnlyRootFilesystem: true
```

It looks to me like you've got a typo in the capability to add. It should be "CAP_SYS_PTRACE".

Cheers,
Lisa
